sqlite:
  :adapter: sqlite
  :database: spec/support/als_typograf_plugin.sqlite.db

sqlite3:
  :adapter: sqlite3
  :database: spec/support/als_typograf_plugin.sqlite3.db

postgresql:
  :adapter: postgresql
  :username: postgres
  :password: postgres
  :database: als_typograf_plugin_test
  :min_messages: ERROR

mysql:
  :adapter: mysql
  :host: localhost
  :username: root
  :password: password
  :database: als_typograf_plugin_test
